language: python
python:
  - "2.7"
install: 
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run -m unittest test
after_success:
  coveralls

notifications:
  slack: b4mad:3FRPPWFHrnVk4hAX88p8p8qu
